### ISSUE TITLE
Add a Getting Started Splash screen on a new career

### ISSUE THREAD

**Issue by rsr427** [abesto/ams2-career#35]
Could we add a quick 1 or 2 page tutorial when a career is new or was just reset?  I think most of the content could come from the wiki, so someone could at least know what we're doing without the extra step.  Here's what it could read:

Page 1
Welcome to the Automobilista 2 Career Simulator!! From here you can record your career through the world of AMS2.

On the **_Go Racing_** tab, you can review your list of potential offers. While you start at the lowest levels of each motorsports discipline, you gain XP for each race in which you participate.

The right of the dashboard will display your current progress in the selected discipline as well as the suggested settings to be used in the race.  

Note on the AI strength: one of the goals of this simulator is ensuring that you have fun and competitive races.  **You do not need to win every race at 101 AI level to progress!!**  (Just pretend your father owns a fertilizer company and helps you move up the ladder...)  If you find you need to bump the AI up (or down) to get a fair challenge, then you can log those adjustments into the simulator to ensure that future races are better calibrated.  You can apportion that increase (or decrease) to ALL cars, one DISCIPLINE, one CLASS, or one CAR, whichever you think best represents the AI balancing needed.

Also note that the simulator will compare your result to the AI level and adjust it for further balancing in that car.  These adjustments are per car, so use the "Global" adjustment to have future offers reflect a better starting AI level.

Go to Enter Results

Page 2

When the race has been completed and the champagne (or tears) has dried from your overalls, enter into the simulator the car your drove and the result achieved.

The model will analyze your performance and the car in which it was achieved and will calculate and apply XP points across all disciplines (but most effectively in the discipline raced).  

The _**Career**_ tab will display your statistics and progress across all disciplines, as well as a full race log for reference.

Also, you can export your career save to protect it against accidental loss.  Or to transport to another computer, browser, or device (did we mention this works on tablets and phones!?).

Pro tip: Don't forget to take advantage of AMS2's brilliant weather and day/night progression system by altering the session conditions in game.  

Good luck and be safe!

**Comment by abesto** [comment]
![image](https://user-images.githubusercontent.com/59982/165931944-f3cd5e76-4048-41cd-846e-a6410b6b0624.png)
![image](https://user-images.githubusercontent.com/59982/165931964-55ea37b8-4413-4c0e-a480-74865a33c50a.png)
