### ISSUE TITLE
Edits to the Post Race pop up

### ISSUE THREAD

**Issue by rsr427** [abesto/ams2-career#37]
1) 2 carriage returns betweenXP earned and a promotion notice:
""With that result you've earned xxx XP in Vintage.

Congratulations!  You have been upgraded to Grade A in Vintage!!""

2) Or, Could promotions that occur at the same time appear below it so it reads:

""With that result you've earned xxx XP in Vintage.

Congratulations!  
You have been upgraded to Grade A in Vintage!!
You have been upgraded to Grade B in Touring!!""

3) Future enhancement: enter a congratulatory comment based on results from the Achievements tab in the shared workbook.  There's commentary there too to accompany Grade promotions in each discipline as well.

**Comment by abesto** [comment]
https://github.com/abesto/ams2-career/commit/04dedb1a8f008defa0c1fe861cef4905c2a500e7 moves the grade-up message to a new line:
![image](https://user-images.githubusercontent.com/59982/165924016-2e937285-c730-4ae3-bd2a-43d1b495eabb.png)

Currently we only show the message for the grade in which the race was run. I've filed #41 to fix this.

Flavor text on grade-up is tracked in #21.

Achievements / badges are tracked in #22.

With that I think everything here is covered, so closing!
