### ISSUE TITLE
Offer an "Accelerated Career" Option

### ISSUE THREAD

**Issue by rsr427** [abesto/ams2-career#42]
Maybe when a new career is started, there is an option for enhanced XP earning.  Maybe scale up the XP earning values to 1.5X the normal? Allows players to progress a little quicker so they can re-run careers and compare them.  (Maybe only I'm that type...)  You could call it "Second Generation Driver Mode", since most 2nd gen drivers are spoiled brats who progress more easily than others, IMO.  :)

**Comment by abesto** [comment]
This should be close to trivial add - it needs a checkbox that enables a 1.5 multiplier in the function that calculates XP gains per race. I guess we could even have a number field for an arbitrary multiplier. The beauty of the current design of the app is that you can mess with the multiplier, and your progress will be re-calculated accordingly, so you can freely change this mid-career (as long as you don't mind having races in your logbook for grades you haven't unlocked yet, when adjusting the multiplier down).

This is also a good starting point for #44

**Comment by rsr427** [comment]
Method 1 for "Mastery":

Club:
Average race at the top level nets 1 XP point
10 more XP points in Club or 5 Podiums in Club and you get inducted to the Club Racing Hall of Fame

Endurance:
Average race at the top level nets 9 XP points
50 more XP points in Club or 3 Podiums in Club and you get inducted to the Endurance Racing Hall of Fame

GT:
Average race at the top level nets 7.5 XP points
50 more XP points in GT or 3 Podiums in GT and you get inducted to the GT Racing Hall of Fame

Karting:
Average race at the top level nets 0.1 XP points
1 more XP points in Karting or 5 Podiums in Karting and you get inducted to the Karting Racing Hall of Fame

Open Wheel:
Average race at the top level nets 10 XP points
100 more XP points in Open Wheel or 5 Podiums in Open Wheel and you get inducted to the Open Wheel Racing Hall of Fame

Special:
Average race at the top level nets 3 XP points
12 more XP points in Special or 3 Podiums in Special and you get inducted to the Special Racing Hall of Fame

Touring:
Average race at the top level nets 5.4 XP points
50 more XP points in Touring or 5 Podiums in Touring and you get inducted to the Touring Racing Hall of Fame

Vintage:
Average race at the top level nets 6.4 XP points
40 more XP points in Vintage or 3 Podiums in Vintage and you get inducted to the Vintage Racing Hall of Fame



Method 2: Reaching the pinnacle unlocks a championship creator button where the season is generated at random from appropriate tracks.
Use class and car adjusted AI.  Report back to the program.  Get an achievement for being Champion.  (Adjust AI depending on season finish?)  Still use formula above for HOF achievement


Club:
8 race championship

Endurance:
6 race championship

GT:
8 race 

Karting:
12 race championship

Open Wheel:
16 race championship

Special:
8 race championship

Touring:
12 race championship

Vintage:
6 race championship

**Comment by abesto** [comment]
@rsr427 I'm confused, did you meant to post this on #47?

**Comment by rsr427** [comment]
Probably both.  I don't where to chat anymore...  It was probably more of an internal discussion.

**Comment by abesto** [comment]
Released in v1.2.0
