### ISSUE TITLE
Jacarepagua shows up as karting tracks

### ISSUE THREAD

**Issue by weissm2040** [abesto/ams2-career#46]
**Describe the bug**
I got given Jacarepagua Kart Three as a karting track, but no such track exists in the game. 

**Expected behavior**
Only valid tracks in the game should be shown

**Additional context**
I believe from the data files that the tracks should be Interlagos Kart 1-3

**Comment by abesto** [comment]
Thank you for the report, right you are! Fix is rolling out now.
