### ISSUE TITLE
Optional feature request

### ISSUE THREAD

**Issue by CaptainSlow72** [abesto/ams2-career#48]
Hi,
here is an optional very low priority feature request:
What do you guys think about a switch to enable/disable gaining XP also for other series when recoding a race result of a specific series?

In its currect state, you also gain some amount of XP for series you did not drive, every time a race result is recorded.
As side effect you climb up the ladder of a series, even if you never have driven a single race of this series.

**Comment by abesto** [comment]
Good to know there's interest in this; I've moved this from "maybe" to "definitely" in #11. Closing this to avoid duplication.

Thanks for taking the time to write down these ideas, @CaptainSlow72! Having feedback way better than assuming what works for us will work for everyone :) cc @all-contributors

**Comment by abesto** [comment]
Hm, that didn't seem to work. @all-contributors please add @CaptainSlow72 for ideas.

**Comment by abesto** [comment]
(Released in v1.2.0)
