### ISSUE TITLE
Disabled cross-discipline gains no XP anymore

### ISSUE THREAD

**Issue by CaptainSlow72** [abesto/ams2-career#54]
**Describe the bug**
When cross-discipline is unchecked, no XP is gained anymore.

**To Reproduce**
1. Uncheck cross-discipline in settings tab
2. Record a race. No XP are gained anymore for this discipline.

**Expected behavior**
XP are gained after recording a race for this discipline, but not for any other disciplines.

**Comment by abesto** [comment]
Omg. Guess I only checked that there was no cross-discipline gain, and never checked that there *is* gain in the same discipline. Should be a simple fix (he said, confidently...) Thank you for the report.

**Comment by abesto** [comment]
Fix should be live in a few minutes. @all-contributors let's add @CaptainSlow72 to the contributors list for bug reports as well, while we're at it.

**Comment by abesto** [comment]
@CaptainSlow72 Fix has rolled out, and AFAICT it's now working as intended. Feel free to reopen if something is still off. (A changelog popup on reload will tell you that you actually got the new version loaded)

**Comment by CaptainSlow72** [comment]
Successfully tested. Seems to work as intended now. Thanks for the fast fix.
